### ISSUE TITLE
TTN V3 Compatability

### ISSUE THREAD

**Issue by BNNorman** [computenodes/dragino#7]
Will this code be compatible with TTN V3? I understand TTN are switching to V3 in September this year.

I used this code & the dragino HAT for a project and would like to know if there would be any problems to overcome.

Many Thanks

**Comment by pjb304** [comment]
I've briefly tested the code against TTN v3 and it works in the UK.  I used MAC 1.0.2 and PHY1.0.2A.

I found it much more reliable using OTAA activation than using ABP.  If using ABP the network would regularly not forward the message on to the correct application despite it being received by the network.

Version 0.0.5 now has improved OTAA handling because of this (it caches the credentials).  v3 also only seems to accept joins on a subset of channels so that restriction is put in for joins, it can then use all available channels for transmission once the join is complete.

There may be other issues that I have yet to encounter, but it looks like it should be ok at the moment.

**Comment by BNNorman** [comment]
Ok, good to know. Thanks.
